syntax = "proto3";

package spotify.api;

option optimize_for = CODE_SIZE;
option java_package = "com.spotify.api";

message ConcertRequest {
  string id = 1;
}

message ConcertResponse {
  message Artist {
    string name = 1;
    string image = 2;
    string id = 3;
  }

  message Date {
    string time = 1;
    int64 unknown = 2;
  }

  message Genre {
    string name = 1;
    string conceptUri = 2;
    string concertsGenreUri = 3;
  }

  message ConcertInfo {
    string colorCode = 1;
    Artist artist = 2;
    string id = 3;
    string artistName = 4;
    Date date = 5;
    string fullLocation = 6;
    string venueName = 8;
    string cityCountry = 9;
    repeated Genre genres = 11;
  }

  message Playlist {
    string artistName = 1;
    string name = 2;
    string image = 3;
    string uri = 4;
    int64 unknown = 5;
  }

  message PlaylistContainer {
    Playlist playlist = 2;
  }

  message DateInfo {
    Date date = 1;
  }

  message VenueMapService {
    int64 id = 1;
    string url = 2;
  }

  message Venue {
    string venueName = 1;
    string venueLocation = 2;
    repeated VenueMapService mapServices = 4;
  }

  message VenueInfo {
    Venue venue = 1;
    DateInfo dateInfo = 2;
  }

  message TicketServiceInfo {
    string companyName = 1;
    string companyBranding = 2;
    string bookUrl = 3;
  }

  message TicketInfo {
    TicketServiceInfo ticketServiceInfo = 2;
    string disclaimer = 5;
  }

  message Section {
    optional string name = 1;
    optional TicketInfo ticketInfo = 3;
    optional PlaylistContainer playlistContainer = 5;
    optional VenueInfo venueInfo = 8;
  }

  ConcertInfo concertInfo = 1;
  repeated Section sections = 2;
}

message Concerts {
  message Header {
    string image = 1;
    string title = 2;
    Location location = 3;
  }

  message Location {
    string name = 1;
    int64 unknown = 2;
  }

  message Date {
    string time = 1;
    int64 unknown = 2;
  }

  message SectionDescription {
    string text = 1;
  }

  message ArtistConcertConcert {
    string artist = 1;
    string locationName = 2;
    string concertUri = 3;
    Date date = 4;
  }

  message ArtistConcerts {
    string name = 1;
    string image = 2;
    string uri = 3;
    repeated ArtistConcertConcert concerts = 4;
  }

  message Artist {
    string name = 1;
    string image = 3;
    Date from = 4;
    Date to = 5;
    ArtistConcerts artistConcerts = 6;
  }

  message Concert {
    string artist = 1;
    string locationName = 2;
    string artistImage = 3;
    string concertUri = 4;
    Date date = 5;
  }

  message ArtistsContainer {
    optional Concert concert = 2;
    optional Artist artist = 3;
  }

  message UNKNContainer {
    repeated ArtistsContainer artists = 1;
  }

  message SectionsContainer {
    string id = 1;
    SectionDescription description = 2;
    repeated UNKNContainer artistContainer = 4;
  }

  message UNKNSectionsContainer {
    repeated SectionsContainer sectionsContainer = 1;
  }

  Header header = 1;
  UNKNSectionsContainer sectionsContainer = 2;
}
